[build]
  command = "cd client && npm install --legacy-peer-deps && npm install @babel/plugin-proposal-private-property-in-object --save-dev && npm run build --legacy-peer-deps && cd .. && node server/server.js"
  publish = "client/build"